version: '3.8'

services:
  langfuse-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langfuse
    ports:
      - "5432:5432"

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@langfuse-db:5432/langfuse
      NEXTAUTH_SECRET: secret123
      NEXTAUTH_URL: http://localhost:3000
      SALT: salthere
      TELEMETRY_ENABLED: false
    ports:
      - "3000:3000"
    depends_on:
      - langfuse-db

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port
